#!/bin/bash

run_list() {

cat <<EOT

Linux dotfiles - Patrick Flor, via @necolas - http://nicolasgallagher.com/

Additional software to install

Browsers:
    Firefox
    Google Chrome
    Opera

Development:
    Filezilla
    VirtualBox
    XAMPP

Other:
    Dropbox
    Network Connect
    Skype
    uTorrent
    VLC
EOT

}
