#!/bin/bash

# Header logging
e_header() {
    echo
    maybe_tput 7   "$@"
}

# Success logging
e_success() {
    maybe_tput 64  "✓" "$@"
}

# Error logging
e_error() {
    maybe_tput 1   "x" "$@"
}

# Warning logging
e_warning() {
    maybe_tput 136 "!" "$@"
}

# Ask for confirmation before proceeding
seek_confirmation() {
    if [ -z $PS1 ]; then
        REPLY="y"
        return
    fi
    printf "\n"
    e_warning "$@"
    read -p "Continue? (y/n) " -n 1
    printf "\n"
}

# Test whether the result of an 'ask' is a confirmation
is_confirmed() {
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
      return 0
    fi
    return 1
}

# Test whether we're in a git repo
is_git_repo() {
    $(git rev-parse --is-inside-work-tree &> /dev/null)
}

# Test whether a command exists
# $1 - cmd to test
type_exists() {
    if [ $(type -P $1) ]; then
      return 0
    fi
    return 1
}
