#!/bin/bash

# General TODO: break this out distro-wise
# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Short form, colored and type indicated by color
alias l="ls --color -F"
# Order by last modified, long form no user group, color
alias lt="ls --color -to"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls --color -AFoh"
# List all except . and .., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls --color -AFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# TODO: need to find adequate equivalents of following commands for each distro)
# IP addresses
# alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
# alias localip="ifconfig getifaddr en1"

# Copy my public key to the pasteboard 
# alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
# alias flushdns="dnscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# TODO: Make this work on more than Ubuntu, if necessary.
# alias emptytrash="sudo rm -rfv ${HOME}/.local/share/Trash/*; sudo rm -rfv /root/.local/share/Trash/*"

# Show/hide hidden files in Finder
# alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
# alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
# alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
# alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
